### ISSUE TITLE
[Feature]: Implement HttpClient class

### ISSUE THREAD

**Issue by jlenon7** [AthennaIO/Common#1]
### 🚀 Feature Proposal

The `HttpClient` class will be responsible to make http requests to other services. With this class, we should be able to define global settings to use in all requests that use the `HttpClient` class. This global settings will be based in [`HttpClientBuilder`](https://javadoc.io/doc/org.apache.httpcomponents.client5/httpclient5/5.0.1/index.html) of [Apache](https://www.apache.org/), and we should be able to set a global instance of this builder for all `HttpClient` or create another instance of `HttpClient` using different `HttpClientBuilder` instances.

### Motivation

Nowadays in Athenna if the developer needs to make any Http request he will need to use the vanilla [http](https://nodejs.org/api/http.html) or [https](https://nodejs.org/api/https.html) of [Node.js](https://nodejs.org/en/) or some library like [axios](https://www.npmjs.com/package/axios) or [node-fetch](https://www.npmjs.com/package/node-fetch). It would be nice if Athenna has her own implementation to do that.

**Comment by jlenon7** [comment]
@RobsonTrasel I have made a mistake, I changed the remote of my local repository from HTTP to SSH, but I didn't realize that it was from AthennaIO/Common and not from your fork, so when I pushed the code, it went to the main repository and not to your fork. 😅

Could you please pull the new code in your fork and open a new PR?

**Comment by RobsonTrasel** [comment]
No problems, I'll be open a new PR.

**Comment by RobsonTrasel** [comment]
@jlenon7 reopened!!

**Comment by RobsonTrasel** [comment]
I'll review some tasks tomorrow, because i'm full time focused in another project!!
